# finding maximum and minimum value in a matrix


In [1]:
#loading libraries
import numpy as np

In [2]:
#create matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
#getting max value in the matrix
np.max(matrix)

9

In [5]:
#getting min value
np.min(matrix)

1

In [6]:
#finding the max value in each column
np.max(matrix, axis=0)

array([7, 8, 9])

In [7]:
#finding max value in each row
np.max(matrix, axis=1)

array([3, 6, 9])

# Calculating variance,average and standard deviation

In [8]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
#getting the mean
np.mean(matrix)

5.0

In [10]:
#getting the variance
np.var(matrix)

6.666666666666667

In [11]:
#getting the standard deviation
np.std(matrix)

2.581988897471611

# Reshaping a matrix

In [12]:
#create a 4x3 matrix
myMatrix = np.array([[1,2,3], [4,5,6],[7,8,9], [10,11,12]])
myMatrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [13]:
#reshape into a 2X6 matrix
myMatrix.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [14]:
#note the size should be the same as the original matrix
myMatrix.size

12

# Transposing a matrix

In [15]:
myMatrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [16]:
#transposing using the T method
myMatrix.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

# flattening a matrix

In [17]:
myMatrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [18]:
#using flatten method
myMatrix.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Finding the rank of a matrix

In [19]:
myMatrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [21]:
#using numpy linear algebra method
np.linalg.matrix_rank(myMatrix)

2

## determinant of a matrix

In [22]:
np.linalg.det(myMatrix)

LinAlgError: Last 2 dimensions of the array must be square