# Working with matrices using Numpy

#load the numpy library
import numpy as np

In [3]:
#create a matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [4]:
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
#selecting 2 from the matrix
matrix[0,1]

2

In [6]:
matrix[2,2]

9

In [7]:
matrix[1,2]

6

In [8]:
#creating an array
myArray = np.array([2,5,3,1,8,10,13,15])

In [9]:
#select all elements
myArray[:]

array([ 2,  5,  3,  1,  8, 10, 13, 15])

In [11]:
#select all elements upto and including 10
myArray[:6]

array([ 2,  5,  3,  1,  8, 10])

In [12]:
#select all elements after the 4th element
myArray[3:]

array([ 1,  8, 10, 13, 15])

In [13]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
#select the first two rows and the second column of the matrix
matrix[:2,1:2]

array([[2],
       [5]])

# Describing a Matrix

In [16]:
#create a matrix
myMatrix = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
myMatrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
#view the shape of the matrix
myMatrix.shape

(3, 4)

In [19]:
#view no of elements
myMatrix.size

12

In [20]:
#view the dimension
myMatrix.ndim

2