In [34]:
import numpy as np
import pandas as pd

In [18]:
a1 = np.array([2,4,6,89,56])

In [19]:
type(a1)

numpy.ndarray

In [25]:
a2 = np.array([[1.4, 2.6, 3.9],
      [4.0, 5.4, 6.7]])


In [26]:
a2

array([[1.4, 2.6, 3.9],
       [4. , 5.4, 6.7]])

In [22]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 16, 17]]])

In [23]:
#getting size, shape and dimension

In [27]:
a1.shape, a2.shape,a3.shape

((5,), (2, 3), (2, 3, 3))

In [28]:
a1.size, a2.size, a3.size

(5, 6, 18)

In [29]:
type(a1),type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [31]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

# creating a dataframe from pandas

In [35]:
df = pd.DataFrame(a2)

In [36]:
df

0    1    2
0  1.4  2.6  3.9
1  4.0  5.4  6.7

## creating numpy arrays

In [37]:
array_ones = np.ones((2, 3, 3))

In [38]:
array_ones

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [41]:
array2 = np.ones((2, 4, 4))

In [42]:
array2

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [43]:
array2.dtype

dtype('float64')

In [44]:
type(array2)

numpy.ndarray

In [45]:
#filled with zeroes

In [50]:
zero_array = np.zeros((2,3))

In [51]:

zero_array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [52]:
#range array

In [53]:
range_arr = np.arange(0, 10, 2)
range_arr

array([0, 2, 4, 6, 8])

In [54]:
#using randint

In [56]:
rand_arr = np.random.randint(0, 10, size=(3,5))
rand_arr

array([[4, 3, 7, 5, 1],
       [6, 8, 4, 2, 7],
       [5, 7, 4, 9, 4]])

In [57]:
rand_arr2 = np.random.randint(0,10, size= (2,2))

In [59]:
rand_arr2


array([[7, 0],
       [5, 9]])

In [60]:
#using random.random

In [63]:
rand_arr3 = np.random.random((3,5,3)) *10
rand_arr3

array([[[2.57614611, 6.19921329, 6.22625531],
        [8.66364133, 4.94043173, 6.93409891],
        [2.97316232, 3.02188597, 9.03021615],
        [8.19822389, 9.00604512, 3.79445458],
        [5.16196589, 7.59401605, 5.56519473]],

       [[8.34193879, 5.90161918, 9.40195383],
        [2.64199707, 4.77558862, 6.61656497],
        [6.79585162, 6.49358869, 3.19834285],
        [1.2897583 , 3.25275486, 2.71631044],
        [5.48947219, 6.55621594, 6.6563298 ]],

       [[6.54804096, 5.08694407, 8.49717515],
        [4.82833371, 7.1782831 , 5.94195984],
        [6.6501022 , 9.40863301, 0.38558953],
        [1.09020414, 9.96497712, 3.17563039],
        [0.01844414, 7.08664248, 1.97927272]]])

# seed